import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Header from "./components/layouts/header/Header";
import "./globals.css";
import { UiProvider } from "./UiProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <UiProvider>
          <Header />
          <main>{children}</main>
        </UiProvider>
      </body>
    </html>
  );
}
